dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
cache:
  directories:
    - ./node_modules
  
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower
- npm install
- bower install

script:
  - npm update & npm cache clean --force
  - npm run test:unit
  - npm run e2e
