dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
cache:
  directories:
    - ./node_modules
  
install:
- npm install

script:
  - npm update & npm cache clean --force
  - node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng test -- --no-watch --no-progress --browsers=Firefox
  - node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng e2e
